import "./globals.css";
import Header from "../components/header/header.js";
import { Arimo } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const arimo = Arimo({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap" /* mostra uma fonte alternativa enquanto essa é carregada */,
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={arimo.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
