import "./globals.css";
import Header from "../components/header/header.js";
import Footer from "../components/footer/footer.js";
import { urbanist } from "@/fonts/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
